"""adding student

Revision ID: 2559ba58f0d3
Revises: 52db072dfd49
Create Date: 2023-08-23 13:19:04.555931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2559ba58f0d3'
down_revision: Union[str, None] = '52db072dfd49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('student_image', sa.String(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('qr_code', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('student_profession_id', sa.Integer(), nullable=True),
    sa.Column('student_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['student_profession_id'], ['professions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('change_change_year_fkey', 'change', type_='foreignkey')
    op.drop_column('change', 'change_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change', sa.Column('change_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('change_change_year_fkey', 'change', 'study_year', ['change_year'], ['id'])
    op.drop_table('students')
    # ### end Alembic commands ###
