version: '3.8'
services:

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-tier

  postgres_database:
    container_name: postgres_container
    image: 'bitnami/postgresql:latest'
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=testdb
    ports:
      - "5432"
    volumes:
      - postgres_container:/var/lib/postgresql/data/
    networks:
      - app-tier

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8888:80"
    volumes:
      - pgadmin4:/var/lib/pgadmin
    networks:
      - app-tier

volumes:
  postgres_container:
  pgadmin4:

networks:
  app-tier:
    driver: bridge
